Pull request almetate to develop
Milinkov-N/c2_s21_stringplus_00 pull request #1
Opened 2022-11-18 12:45 UTC by KolyaDavydov

добавлена s21_memchr

```c
void *s21_memchr(const void *str, int c, s21_size_t n) {
  // приравниваем изначально к нашему s21_NULL
  unsigned char *res = s21_NULL;

  //создаем переменную ptr типа char которая хранит адрес начала строки
  const unsigned char *ptr = str;

  for (int i = 0; i < (int) n; i++) {
    if(*ptr == (unsigned char) c) {
      res = *ptr;
    } else {
      ptr++;
    }
  }
  return res;
}
```

2022-11-18 13:11 UTC, Milinkov-N commented on src/Makefile
> +	$(CC) $(CFLAGS) $(CHECKFLAGS) $(LDFLAGS) s21_string.a tests.o -o run
Нужно добавить пустую между целями  `test` и `s21_string.a`

2022-11-18 13:14 UTC, Milinkov-N commented on src/Makefile
> +	$(CC) $(CFLAGS) $(CHECKFLAGS) $(LDFLAGS) s21_string.a tests.o -o run
Хотя нет, ничего трогать не нужно, видимо не те изменения посмотрел. В Мейке все хорошо

2022-11-18 13:27 UTC, Milinkov-N requested changes
В целом все хорошо, однако бинарные файлы лучше не пушить в репозиторий.

Так как ты уже замержил `develop` ветку в свою, файлы `.gcda` и `.gcno` у тебя заигнорены. Чтобы они пропали из репозитория, тебе нужно _**убрать их из файла `.gitignore`, затем удалить и сделать коммит.**_

После этих действий тебе снова _**нужно будет добавить файлы `.gcda` и `.gcno` в  `.gitignore`.**_

И добавь также в `.gitignore` свой файл `main.c` и его бинарник `main`.

Все это нужно для того, чтобы эти ненужные файлы не оказались в ветке `develop` и ты при этом мог с ними продолжать спокойно работать.

2022-11-19 06:58 UTC, KolyaDavydov commented
В ветке _**almetate**_ удалены бинарники, добавлены в **.gitignore** файлы _main_ и _main.c_

2022-11-21 09:27 UTC, Milinkov-N commented on src/Makefile
>  all: gcov_report.html
Цель all должна собирать не только `gcov_report`, но и цель `s21_string.a`, которой тут не хватает, кстати

2022-11-21 09:40 UTC, Milinkov-N approved these changes
Все отлично!

2022-11-21 09:40 UTC, Milinkov-N commented on src/tests.c
> +Suite *ts_s21_memmove() {
Сьюты лучше помещать в конце файла после всех тест-кейсов для каждой функции, иначе будет очень неудобно ориентироваться по файлу, особенно учитывая какой длины он будет в итоге. Нумерация самих тест-кейсов должна быть глобальная.

Но все это пока не критично, в целом я могу сам это все подправить, а пока зачёт.

2022-11-21 09:42 UTC, merged